name: truesip-website
region: nyc

static_sites:
  - name: web
    source_dir: /
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
    routes:
      - path: /
